### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method PhpParser\Node\Expr\Variable::getFirst() in /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/GenProxiedClassFileHelper.php:60 

### ISSUE THREAD

**Issue by marty-macfly** [pinpoint-apm/pinpoint-php-aop#16]
I'm using `pinpoint-php-aop` v2.0.1 and I've got the following exception:

```
Warning: assert(): assert($node instanceof Node\Name) failed in /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/GenProxiedClassFileHelper.php on line 55

Fatal error: Uncaught Error: Call to undefined method PhpParser\Node\Expr\Variable::getFirst() in /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/GenProxiedClassFileHelper.php:60 Stack trace:
 #0 /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/GenProxiedClassFileHelper.php(75): pinpoint\Common\GenProxiedClassFileHelper->getRealNp(Object(PhpParser\Node\Expr\Variable))
 #1 /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/GenProxiedClassFileHelper.php(112): pinpoint\Common\GenProxiedClassFileHelper->renderClassName(Object(PhpParser\Node\Expr\Variable), Array)
 #2 /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/CodeVisitor.php(92): pinpoint\Common\GenProxiedClassFileHelper->handleEnterNew_(Object(PhpParser\Node\Expr\New_))
 #3 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): pinpoint\Common\CodeVisitor->enterNode(Object(PhpParser\Node\Expr\New_))
 #4 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Objec in /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/GenProxiedClassFileHelper.php on line 60
```

**Comment by eeliu** [comment]
@marty-macfly 

Could you attach the rendered file(or class file) by pinpoint-php-aop? 
It will help to address the problem.

Best regard!

**Comment by marty-macfly** [comment]
I'm working on those https://github.com/marty-macfly/yii2-pinpoint-plugin they were ok with pinpoint-php-aop version 1 I try to move to version 2 and I now face that issue.

**Comment by eeliu** [comment]
@marty-macfly 
hmm, composer update failed !
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2[2.0.5, 2.0.6] require bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> could not be found in any version, but the following packages provide it:
      - craftcms/cms Craft CMS
      - yidas/yii2-bower-asset Bower Assets for Yii 2 app provided via Composer repository
      - yidas/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - yidas/yii2-jquery jQuery Asset Bundle extension with fixed and CDN sources for Yii2 framework
      - jamband/yii2-ensure-unique-behavior This extension insert unique identifier automatically for the Yii 2 framework
      - taobig/php-helper A tool set for PHP projects
      - demokn/yii2-composer-asset
      - maiscrm/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
```

**Comment by marty-macfly** [comment]
Need to get a [yii basic application](https://www.yiiframework.com/doc/guide/2.0/en/start-installation#installing-from-composer) and after add my extension in `composer.json`.

**Comment by eeliu** [comment]
@marty-macfly 

This is the example for yii2

https://github.com/pinpoint-apm/pinpoint-c-agent/tree/master/plugins/PHP/Plugins/Framework/yii2

> pinpoint-php-aop v2.x supports zore intrusion on Yii2 framework. while, you must follow the plugin template.

**Comment by eeliu** [comment]
Does this line is enough to run your plugin ?

`composer create-project --prefer-dist yiisoft/yii2-app-basic basic`

**Comment by eeliu** [comment]
> Need to get a [yii basic application](https://www.yiiframework.com/doc/guide/2.0/en/start-installation#installing-from-composer) and after add my extension in `composer.json`.

This is our demo for test yii2

https://github.com/eeliu/pinpoint-in-yii2

**Comment by marty-macfly** [comment]
I've done more investigation and issue is coming from [src/plugins/DbPlugin.php](https://github.com/marty-macfly/yii2-pinpoint-plugin/blob/main/src/plugins/DbPlugin.php#L6) those 2 specifics hook:

* `///@hook:yii\db\Connection::open`
* `///@hook:yii\db\Connection::close`

If I remove them error disappear.

**Comment by eeliu** [comment]
##  v2.0.1 supports namespace replace

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/bb9e4f2a333e0cd69d21f89790382eb0c1f2318a/plugins/PHP/Plugins/Framework/yii2/setting.ini#L3-L13

So, there is no needs to `@hook` all the upper level function/class, just replace `PDO=Plugins\Sys\PDO\PDO` within `class_name[]=Spiral\Database\Driver\Driver`

**Comment by marty-macfly** [comment]
Hello,

Happy new year, all the best. Do you mean like that :

```ini
[nm_class]
PDO=Plugins\Sys\PDO\PDO
[nm_func]
[nm_string]
[nm_add_class]
class_name[]=yii\db\Command
[nm_ignore_class]
```

**Comment by eeliu** [comment]
> Hello,
> 
> Happy new year, all the best. Do you mean like that :
> 
> ```ini
> [nm_class]
> PDO=Plugins\Sys\PDO\PDO
> [nm_func]
> [nm_string]
> [nm_add_class]
> class_name[]=yii\db\Command
> [nm_ignore_class]
> ```

Yes

**Comment by marty-macfly** [comment]
When I'm doing that I don't have PDO information in the UI.

**Comment by marty-macfly** [comment]
Ok, it doesn't do anything it's because `yii\db\Command` doesn't use PDO, I need to set it to `yii\db\Connection` and when I do that:

```
PHP Warning:  assert(): assert($node instanceof Node\Name) failed in /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/GenProxiedClassFileHelper.php on line 55
PHP Stack trace:
PHP   1. {main}() /app/yii:0
PHP   2. require_once() /app/yii:12
PHP   3. require_once() /app/vendor/macfly/yii2-pinpoint-plugin/src/yii.php:23
PHP   4. pinpoint\Common\PinpointDriver->init($classMap = class pinpoint\Common\AopClassMap { protected $index_file_path = '/app/vendor/macfly/yii2-pinpoint-plugin/src/../../../../runtime/pinpoint/cache/__class_index_table'; private $cached = FALSE; private $classLoaderMap = [] }) /app/vendor/pinpoint-apm/pinpoint-php-aop/auto_pinpointed.php:18
PHP   5. pinpoint\Common\OriginFileVisitor->runAllVisitor($fullPath = '/app/vendor/yiisoft/yii2/db/Connection.php', $aopFuncInfo = [], $naming = ['classCall' => ['PDO' => 'Plugins\\Sys\\PDO\\PDO'], 'funCall' => [], 'ignoreFiles' => [], 'appendFiles' => [0 => 'yii\\db\\Connection']]) /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/PinpointDriver.php:110
PHP   6. PhpParser\NodeTraverser->traverse($nodes = [0 => class PhpParser\Node\Stmt\Namespace_ { public $name = class PhpParser\Node\Name { ... }; public $stmts = [...]; protected $attributes = [...] }]) /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/OriginFileVisitor.php:43
PHP   7. PhpParser\NodeTraverser->traverseArray($nodes = [0 => class PhpParser\Node\Stmt\Namespace_ { public $name = class PhpParser\Node\Name { ... }; public $stmts = [...]; protected $attributes = [...] }]) /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:91
```

**Comment by marty-macfly** [comment]
Sorry proper error message is that one:

```
Fatal error: Uncaught Error: Call to undefined method PhpParser\Node\Expr\Variable::getFirst() in /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/GenProxiedClassFileHelper.php on line 60

Error: Call to undefined method PhpParser\Node\Expr\Variable::getFirst() in /app/vendor/pinpoint-apm/pinpoint-php-aop/lib/pinpoint/Common/GenProxiedClassFileHelper.php on line 60
```

**Comment by eeliu** [comment]
Could you please share the "/app/vendor/yiisoft/yii2/db/Connection.php" file to us?

**Comment by marty-macfly** [comment]
Yes, https://github.com/yiisoft/yii2/blob/master/framework/db/Connection.php

**Comment by marty-macfly** [comment]
Failed on that node:

```
PhpParser\Node\Name Object
(
    [parts] => Array
        (
            [0] => InvalidConfigException
        )

    [attributes:protected] => Array
        (
            [startLine] => 613
            [endLine] => 613
        )

)
PhpParser\Node\Name Object
(
    [parts] => Array
        (
            [0] => InvalidConfigException
        )

    [attributes:protected] => Array
        (
            [startLine] => 617
            [endLine] => 617
        )

)
PhpParser\Node\Name Object
(
    [parts] => Array
        (
            [0] => Exception
        )

    [attributes:protected] => Array
        (
            [startLine] => 642
            [endLine] => 642
        )

)
```

**Comment by eeliu** [comment]
@marty-macfly  Thanks， wait a moment ！

**Comment by eeliu** [comment]
@marty-macfly 
I had fix the crash problem. 

But,
```php
  $pdoClass = $this->pdoClass;
        if ($pdoClass === null) {
            $pdoClass = 'PDO';  //<---------is a string 
            if ($this->_driverName !== null) {
                $driver = $this->_driverName;
            } elseif (($pos = strpos($this->dsn, ':')) !== false) {
                $driver = strtolower(substr($this->dsn, 0, $pos));
            }
            if (isset($driver)) {
                if ($driver === 'mssql' || $driver === 'dblib') {
                    $pdoClass = 'yii\db\mssql\PDO';
                } elseif ($driver === 'sqlsrv') {
                    $pdoClass = 'yii\db\mssql\SqlsrvPDO';
                }
            }
        }
```

pdoClass  was assigned by as string, not a class! 

I was tried to support render a "string", but it could bring some side effect. 

If you need this feature (render a string), please let me know!

**Comment by marty-macfly** [comment]
`render a string` won't be necessary I prefer to instrument the upper class instead of bringing unexpected side effect.
